name: Basic 2 File Workflow

# on: [push, pull_request]
on:
  push:
    # branches:
    #   - main

    branches-ignore:
      - main

jobs:
  create-file:
    runs-on: ubuntu-latest
    steps:
      - name: print message
        run: echo "print message"
