name: vars Workflow

on: [push, pull_request]

env:
  APP_NAME: my-app
  ENVIRONMENT: production

jobs:
  execute-task:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: |
          echo "App: $APP_NAME"
          echo "Env: $ENVIRONMENT"
          echo "Course: var.$MY_COURSE_NAME"
          echo "تم استلام الإشارة بنجاح!"
