name: Custome Workflow
on: workflow_dispatch

jobs:
  custome_job:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: :mbstring
