name: Basic Services
on: workflow_dispatch
jobs:
  basic_services_job:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest

    steps:
      - name: Check Redis Service
        run: |
          echo "Waiting for Redis to be healthy..."
          while ! redis-cli ping; do
            sleep 1
          done
          echo "Redis is healthy and ready to use!"
